### ISSUE TITLE
[MODEL]Рефакторинг имен таблиц

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#1]
Изменить имена таблиц - имя должно начинаться с префикса, например **GRP5_**

**Comment by group52** [comment]
Тут вроде просто ,но уточню: было - USERS, стало -  GRP5_USERS.

**Comment by anry-das** [comment]
Да.
Ну и везде, где эти таблички используются, тоже нужно изменить имена.

**Comment by group52** [comment]
Сделал для всех таблиц
