### ISSUE TITLE
[MODEL] Добавить контроль целостности данных

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#12]
Необходимо добавить контроль целостности данных в схему БД (используя FK).
Для этого:
- связать ID и PARTENT_ID в GRP5_ENTITY
- связать GRP5_ENTITY_PARAMETER.ENTITY_ID и GRP5_ENTITY.ID

При создании констрейнтов обязательно указать каскадное удаление

**Comment by group52** [comment]
96a5b76
