### ISSUE TITLE
[REFACTORING] EntityParameterDAO

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#19]
Разнести методы разных сущностей по разным классам.
Вынести checkLogin как отдельный сервис

**Comment by anry-das** [comment]
Еще обратите внимание, что, например
EntityParameter entityParameter = new EntityParameter();
        entityParameter.setParameterId(entityDAO.getId("groupId"));
        entityParameter.setEntityId(studyLoad.getId());
        entityParameter.setIdValue(studyLoad.getGroupId());
лучше все set'ы вынести в конструктор

**Comment by group52** [comment]
Уточните пожалуйста о каких методах идет речь
