### ISSUE TITLE
[MODEL] Скрипты структуры БД

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#2]
Необходимо обновить скрипты создания структуры БД.
Также обратить внимание на то, что сейчас формат скриптов не везде **Oracle**.

**Comment by group52** [comment]
Для пароля,логина и администрирования создавал отдельную таблицу.
DROP TABLE USERS;
create table USERS
(
  USERNAME VARCHAR2(36) not null,
  PASSWORD VARCHAR2(36) not null,
  ROLE_ID   VARCHAR2(50) not null,
  FIRSTNAME VARCHAR(50) not null,
  LASTNAME VARCHAR(50) not null

) ;

Я правильно понимаю,что теперь нужно добавить эту таблицу в файл DBStructure.sql в ветке мастер?

**Comment by anry-das** [comment]
Да.
И еще проверить работоспособность этого скрипта.

**Comment by group52** [comment]
И ещё , я в SQLdeveloper писал запрос:
UPDATE users SET role_id = 'admin' WHERE username = 'Vasya1';
чтобы присвоить роль админ.
А дальше,логинясь под админом можно менять роли других юзеров. Нужно ли этот запрос добавлять в DBStructure.sql?

**Comment by anry-das** [comment]
По идее данные этим скриптом меняться не должны.
Только структура данных.
Так что это добавлять в скрипт не нужно.

**Comment by group52** [comment]
Добавил  таблицу в файл DBStructure.sql в ветку мастер во время мёрджа. Попробовал переименовать в GRP5_USERS - перестало распознавать роли, всех воспринимало как студентов.Так и не понял почему.

**Comment by group52** [comment]
Исправил.
