### ISSUE TITLE
[REFACTORING] LoginController

### ISSUE THREAD

**Issue by das13** [group52/OnlineJournal#22]
Вынести в конструктор установку параметров в коде:
`EntityParameter entityParameter = new EntityParameter();
        entityParameter.setParameterId(entityDAO.getId("login"));
        entityParameter.setEntityId(loginPassword.getUserId());
        entityParameter.setStringValue(loginPassword.getLogin());
        entityParameterDAO.saveParameterDB(entityParameter);
        entityParameter.setParameterId(entityDAO.getId("password"));
        String hashedPassword = passwordEncoder.encode(loginPassword.getPassword());
        entityParameter.setStringValue(hashedPassword);
        entityParameterDAO.saveParameterDB(entityParameter);
        EntityParameter loginParameter = entityParameterDAO.getLoginParameter(loginPassword.getLogin());
        Entity entity = entityDAO.getEntity(loginPassword.getUserId());`

Избегать повторного вызова **entityParameterDAO.saveParameterDB**

**Comment by group52** [comment]
3fa1986
