### ISSUE TITLE
[ADD][MODEL] Функционал создания структуры БД

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#3]
Добавить функционал создания структуры БД, если в текущей базе нет нужных таблиц

**Comment by anry-das** [comment]
Ну да.
В требованиях же есть (п. 10):
"Этот скрипт должен автоматически выполнятся при старте приложения. Если таблицы уже существуют в базе данных, то скрипт не должен завершаться с ошибками и приложение должно продолжать функционировать. Существующие данные в таблицах не должны быть модифицированы. "

**Comment by group52** [comment]
e91b9b9
