### ISSUE TITLE
[ADD] Добавить файл конфигурации приложения

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#4]
Согласно требованиям, добавить в приложение файл **application.propeties**, где будут храниться данные подключения к БД:
URL=
Login=
Password=

**Comment by group52** [comment]
Здесь мне тоже не совсем понятно.
У меня:jdbc:oracle:thin:@localhost:1521:XE
system
12345678
У Наташи - другие. Как правильно прописать?

**Comment by anry-das** [comment]
Вот для того и нужен application.propeties, чтобы раз прописал данные соединения к БД и все.
"Как правильно прописать?"
В стриме можно чтобы этот файл вообще пустым был. Лишь бы он нормально обрабатывался.
